#!/bin/bash

cd "${0%/*}"

time_to_midnight=$(($(date -d 'tomorrow 08:00:00' +%s) - $(date +%s) + 1))
filename=~/logs/statsbot-log-$(date +%F)

timeout $time_to_midnight node app.js | tee -a ~/statsbot-log-complete > ~/statsbot-log 2>> ~/statsbot-errlog

exitval=$?

#update bot
ctr=0
while [ -e $filename-$ctr.gz ]; do
	((ctr++))
done

if [ -s ~/statsbot-log ]; then
	python3 ../stats-lib/anonymize.py ~/statsbot-log > $filename-$ctr 
	gzip $filename-$ctr
	rm $filename-$ctr
fi

rm ~/logs/stats-lib.tar.gz
tar czf ~/logs/stats-lib.tar.gz ~/airmash-logs/stats-lib

git pull
npm install

sleep 5

if [ $exitval -ne 56 ]; then
	# Restart the script with the updated one
	exec "$(which $0)"
fi
